services:
  postgres:
    image: docker.io/library/postgres:17.2-alpine
    restart: unless-stopped
    command: -c 'max_connections=256'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres-data:
