//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "character_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    pub prompt: String,
    pub description: String,
    pub belong_user: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::history_indexes::Entity")]
    HistoryIndexes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::BelongUser",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::history_indexes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistoryIndexes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
