//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::ChatRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "histories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub chat_role: ChatRole,
    pub belong_history_index: Uuid,
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::history_indexes::Entity",
        from = "Column::BelongHistoryIndex",
        to = "super::history_indexes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    HistoryIndexes,
}

impl Related<super::history_indexes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistoryIndexes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
