//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::character_profiles::Entity as CharacterProfiles;
pub use super::histories::Entity as Histories;
pub use super::history_indexes::Entity as HistoryIndexes;
pub use super::users::Entity as Users;
