[package]
name = "chatara-tool"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
openai-api-rs.workspace = true
reqwest.workspace = true
tokio.workspace = true

chatara-storage.workspace = true
