[package]
name = "chatara-storage"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
log.workspace = true
rust-s3.workspace = true
thiserror.workspace = true
tokio.workspace = true
