[package]
name = "migration"

authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration.workspace = true
tokio.workspace = true
